version: 2.1
jobs:
  integration:
    docker:
      - image: circleci/node:10.15.1
    resource_class: medium+
    steps:
      - checkout
      - run: npm ci
      - run: npm run app:lint
      - run: npm run app:test
      - run: npm run app:build
      - save_cache:
          key: repo-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  deploy:
    machine: true
    steps:
      - restore_cache:
          key: repo-build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: heroku push
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a geek-platform web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a geek-platform web
workflows:
  version: 2
  continuous-integration:
    jobs:
      - integration
      - deploy:
          requires:
            - integration
          filters:
            branches:
              only: master