version: 2.1
jobs:
  integration:
    machine: true
    steps:
      - checkout
      - run:
          name: nvm
          command: |
            set +e
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 10.15.2
            nvm use 10.15.2
      - run: npm ci
      - run: npm run app:lint
      - run: npm run app:test
      - run: npm run app:build
      - save_cache:
          key: repo-build-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  deploy:
    machine: true
    steps:
      - restore_cache:
          key: repo-build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: heroku push
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a geek-platform web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a geek-platform web
workflows:
  version: 2
  continuous-integration:
    jobs:
      - integration
      - deploy:
          requires:
            - integration
          filters:
            branches:
              only: master